# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: 'windows-latest' 

steps:

- task: KubectlInstaller@0
  displayName: 'Install Kubectl'
  inputs:
    kubectlVersion: 'latest'

- task: PowerShell@2
  displayName: 'Run PowerShell Script'
  inputs:
    filePath: './kube.ps1' 

