apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-deployment
  labels:
    app: soft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soft
  template:
    metadata:
      labels:
        app: soft
    spec:
      containers:
      - name: soft-container  # Corrected container name
        image: bhargavteja14/soft-landing:latest
        ports:
        - containerPort: 80
