apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-wavecafe
  labels:
    app: wavecafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavecafe
  template:
    metadata:
      labels:
        app: wavecafe
    spec:
      containers:
      - name: wavecafe
        image: bhargavteja14/wavecafe:latest
        ports:
        - containerPort: 80